export enum AuthErrors {
  INVALID_LOGIN = "INVALID_LOGIN",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  TO_MANY_REQUESTS = "TO_MANY_REQUESTS",
  INVALID_EMAIL = "INVALID_EMAIL",
  EMAIL_NOT_FOUND = "EMAIL_NOT_FOUND",
  INVALID_CAPTCHA = "INVALID_CAPTCHA",
  LOGIN_EXISTS = "LOGIN_EXISTS",
  EMAIL_EXISTS = "EMAIL_EXISTS",
  PASSWORD_REPEAT_MISMATCH = "PASSWORD_REPEAT_MISMATCH",
  INVALID_RESPONSE = "INVALID_RESPONSE",
  INVALID_CODE = "INVALID_CODE"
}