export enum AuthErrors {
  EMPTY_EMAIL = 'EMPTY_EMAIL',
  INVALID_EMAIL = 'INVALID_EMAIL',
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
  EMAIL_EXISTS = 'EMAIL_EXISTS',

  EMPTY_PASSWORD = 'EMPTY_PASSWORD',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_OLD_PASSWORD = 'INVALID_OLD_PASSWORD',
  INVALID_PASSWORD_MIN_LENGTH = 'INVALID_PASSWORD_MIN_LENGTH',
  PASSWORD_REPEAT_MISMATCH = 'PASSWORD_REPEAT_MISMATCH',

  EMPTY_CAPTCHA = 'EMPTY_CAPTCHA',
  INVALID_CAPTCHA = 'INVALID_CAPTCHA',

  EMPTY_LOGIN = 'EMPTY_LOGIN',
  INVALID_LOGIN = 'INVALID_LOGIN',
  INVALID_LOGIN_MIN_LENGTH = 'INVALID_LOGIN_MIN_LENGTH',
  INVALID_LOGIN_MAX_LENGTH = 'INVALID_LOGIN_MAX_LENGTH',
  LOGIN_EXISTS = 'LOGIN_EXISTS',

  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TO_MANY_REQUESTS = 'TO_MANY_REQUESTS',
  INVALID_RESPONSE = 'INVALID_RESPONSE',
  INVALID_CODE = 'INVALID_CODE'
}
